package hibernate;

// Generated 1-gen-2014 19.41.13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArgomentiInserzioneId generated by hbm2java
 */
@Embeddable
public class ArgomentiInserzioneId implements java.io.Serializable {

	private int idArgomentiInserzione;
	private int idInsezione;
	private int idArgomento;

	public ArgomentiInserzioneId() {
	}

	public ArgomentiInserzioneId(int idArgomentiInserzione, int idInsezione,
			int idArgomento) {
		this.idArgomentiInserzione = idArgomentiInserzione;
		this.idInsezione = idInsezione;
		this.idArgomento = idArgomento;
	}

	@Column(name = "ID_Argomenti_Inserzione", nullable = false)
	public int getIdArgomentiInserzione() {
		return this.idArgomentiInserzione;
	}

	public void setIdArgomentiInserzione(int idArgomentiInserzione) {
		this.idArgomentiInserzione = idArgomentiInserzione;
	}

	@Column(name = "ID_Insezione", nullable = false)
	public int getIdInsezione() {
		return this.idInsezione;
	}

	public void setIdInsezione(int idInsezione) {
		this.idInsezione = idInsezione;
	}

	@Column(name = "ID_Argomento", nullable = false)
	public int getIdArgomento() {
		return this.idArgomento;
	}

	public void setIdArgomento(int idArgomento) {
		this.idArgomento = idArgomento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArgomentiInserzioneId))
			return false;
		ArgomentiInserzioneId castOther = (ArgomentiInserzioneId) other;

		return (this.getIdArgomentiInserzione() == castOther
				.getIdArgomentiInserzione())
				&& (this.getIdInsezione() == castOther.getIdInsezione())
				&& (this.getIdArgomento() == castOther.getIdArgomento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdArgomentiInserzione();
		result = 37 * result + this.getIdInsezione();
		result = 37 * result + this.getIdArgomento();
		return result;
	}

}
