package hibernate;

// Generated 3-feb-2014 16.30.21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArgomentiInserzioneId generated by hbm2java
 */
@Embeddable
public class ArgomentiInserzioneId implements java.io.Serializable {

	private int idInserzione;
	private int idArgomento;

	public ArgomentiInserzioneId() {
	}

	public ArgomentiInserzioneId(int idInserzione, int idArgomento) {
		this.idInserzione = idInserzione;
		this.idArgomento = idArgomento;
	}

	@Column(name = "ID_Inserzione", nullable = false)
	public int getIdInserzione() {
		return this.idInserzione;
	}

	public void setIdInserzione(int idInserzione) {
		this.idInserzione = idInserzione;
	}

	@Column(name = "ID_Argomento", nullable = false)
	public int getIdArgomento() {
		return this.idArgomento;
	}

	public void setIdArgomento(int idArgomento) {
		this.idArgomento = idArgomento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArgomentiInserzioneId))
			return false;
		ArgomentiInserzioneId castOther = (ArgomentiInserzioneId) other;

		return (this.getIdInserzione() == castOther.getIdInserzione())
				&& (this.getIdArgomento() == castOther.getIdArgomento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdInserzione();
		result = 37 * result + this.getIdArgomento();
		return result;
	}

}
