package hibernate;

// Generated 17-apr-2014 0.21.19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArgomentiInserzioneId generated by hbm2java
 */
@Embeddable
public class ArgomentiInserzioneId implements java.io.Serializable {

	private int idInserzione;
	private String argomento;

	public ArgomentiInserzioneId() {
	}

	public ArgomentiInserzioneId(int idInserzione, String argomento) {
		this.idInserzione = idInserzione;
		this.argomento = argomento;
	}

	@Column(name = "ID_Inserzione", nullable = false)
	public int getIdInserzione() {
		return this.idInserzione;
	}

	public void setIdInserzione(int idInserzione) {
		this.idInserzione = idInserzione;
	}

	@Column(name = "Argomento", nullable = false, length = 30)
	public String getArgomento() {
		return this.argomento;
	}

	public void setArgomento(String argomento) {
		this.argomento = argomento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArgomentiInserzioneId))
			return false;
		ArgomentiInserzioneId castOther = (ArgomentiInserzioneId) other;

		return (this.getIdInserzione() == castOther.getIdInserzione())
				&& ((this.getArgomento() == castOther.getArgomento()) || (this
						.getArgomento() != null
						&& castOther.getArgomento() != null && this
						.getArgomento().equals(castOther.getArgomento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdInserzione();
		result = 37 * result
				+ (getArgomento() == null ? 0 : this.getArgomento().hashCode());
		return result;
	}

}
