package hibernate;

// Generated 21-nov-2013 16.24.11 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Argomenti generated by hbm2java
 */
@Entity
@Table(name = "argomenti", catalog = "supermercati")
public class Argomenti implements java.io.Serializable {

	private Integer idArgomenti;
	private String arg1;
	private String arg2;

	public Argomenti() {
	}

	public Argomenti(String arg1, String arg2) {
		this.arg1 = arg1;
		this.arg2 = arg2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_Argomenti", unique = true, nullable = false)
	public Integer getIdArgomenti() {
		return this.idArgomenti;
	}

	public void setIdArgomenti(Integer idArgomenti) {
		this.idArgomenti = idArgomenti;
	}

	@Column(name = "arg1", length = 30)
	public String getArg1() {
		return this.arg1;
	}

	public void setArg1(String arg1) {
		this.arg1 = arg1;
	}

	@Column(name = "arg2", length = 30)
	public String getArg2() {
		return this.arg2;
	}

	public void setArg2(String arg2) {
		this.arg2 = arg2;
	}

}
