package hibernate;

// Generated 15-apr-2014 23.19.49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ListaSpesaProdotti generated by hbm2java
 */
@Entity
@Table(name = "lista_spesa_prodotti", catalog = "supermercati")
public class ListaSpesaProdotti implements java.io.Serializable {

	private ListaSpesaProdottiId id;
	private Prodotto prodotto;
	private ListaSpesa listaSpesa;
	private Boolean acquistato;
	private String quantità;

	public ListaSpesaProdotti() {
	}

	public ListaSpesaProdotti(ListaSpesaProdottiId id, Prodotto prodotto,
			ListaSpesa listaSpesa) {
		this.id = id;
		this.prodotto = prodotto;
		this.listaSpesa = listaSpesa;
	}

	public ListaSpesaProdotti(ListaSpesaProdottiId id, Prodotto prodotto,
			ListaSpesa listaSpesa, Boolean acquistato, String quantità) {
		this.id = id;
		this.prodotto = prodotto;
		this.listaSpesa = listaSpesa;
		this.acquistato = acquistato;
		this.quantità = quantità;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idSpesa", column = @Column(name = "ID_Spesa", nullable = false)),
			@AttributeOverride(name = "idProdotto", column = @Column(name = "ID_Prodotto", nullable = false)),
			@AttributeOverride(name = "descrizione", column = @Column(name = "Descrizione", nullable = false, length = 45)) })
	public ListaSpesaProdottiId getId() {
		return this.id;
	}

	public void setId(ListaSpesaProdottiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_Prodotto", nullable = false, insertable = false, updatable = false)
	public Prodotto getProdotto() {
		return this.prodotto;
	}

	public void setProdotto(Prodotto prodotto) {
		this.prodotto = prodotto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_Spesa", nullable = false, insertable = false, updatable = false)
	public ListaSpesa getListaSpesa() {
		return this.listaSpesa;
	}

	public void setListaSpesa(ListaSpesa listaSpesa) {
		this.listaSpesa = listaSpesa;
	}

	@Column(name = "Acquistato")
	public Boolean getAcquistato() {
		return this.acquistato;
	}

	public void setAcquistato(Boolean acquistato) {
		this.acquistato = acquistato;
	}

	@Column(name = "Quantità", length = 45)
	public String getQuantità() {
		return this.quantità;
	}

	public void setQuantità(String quantità) {
		this.quantità = quantità;
	}

}
