package hibernate;

// Generated 7-apr-2014 22.47.58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ListaSpesa generated by hbm2java
 */
@Entity
@Table(name = "lista_spesa", catalog = "supermercati")
public class ListaSpesa implements java.io.Serializable {

	private Integer idSpesa;
	private Utente utente;
	private String nomeListaSpesa;
	private Float prezzoTot;
	private Set listaSpesaProdottis = new HashSet(0);

	public ListaSpesa() {
	}

	public ListaSpesa(Utente utente, String nomeListaSpesa) {
		this.utente = utente;
		this.nomeListaSpesa = nomeListaSpesa;
	}

	public ListaSpesa(Utente utente, String nomeListaSpesa, Float prezzoTot,
			Set listaSpesaProdottis) {
		this.utente = utente;
		this.nomeListaSpesa = nomeListaSpesa;
		this.prezzoTot = prezzoTot;
		this.listaSpesaProdottis = listaSpesaProdottis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_Spesa", unique = true, nullable = false)
	public Integer getIdSpesa() {
		return this.idSpesa;
	}

	public void setIdSpesa(Integer idSpesa) {
		this.idSpesa = idSpesa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Utente", nullable = false)
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@Column(name = "NomeListaSpesa", nullable = false, length = 45)
	public String getNomeListaSpesa() {
		return this.nomeListaSpesa;
	}

	public void setNomeListaSpesa(String nomeListaSpesa) {
		this.nomeListaSpesa = nomeListaSpesa;
	}

	@Column(name = "Prezzo_Tot", precision = 12, scale = 0)
	public Float getPrezzoTot() {
		return this.prezzoTot;
	}

	public void setPrezzoTot(Float prezzoTot) {
		this.prezzoTot = prezzoTot;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listaSpesa")
	public Set getListaSpesaProdottis() {
		return this.listaSpesaProdottis;
	}

	public void setListaSpesaProdottis(Set listaSpesaProdottis) {
		this.listaSpesaProdottis = listaSpesaProdottis;
	}

}
