package hibernate;

// Generated 10-dic-2013 16.19.44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Prodotto generated by hbm2java
 */
@Entity
@Table(name = "prodotto", catalog = "supermercati", uniqueConstraints = @UniqueConstraint(columnNames = "CodiceBarre"))
public class Prodotto implements java.io.Serializable {

	private Integer idProdotto;
	private Sottocategoria sottocategoria;
	private int codiceBarre;
	private String descrizione;
	private Integer idArg;
	private Integer arg1;
	private Integer arg2;
	private Set inserziones = new HashSet(0);
	private Set listaDesideriProdottis = new HashSet(0);
	private Set listaSpesaProdottis = new HashSet(0);

	public Prodotto() {
	}

	public Prodotto(Sottocategoria sottocategoria, int codiceBarre,
			String descrizione) {
		this.sottocategoria = sottocategoria;
		this.codiceBarre = codiceBarre;
		this.descrizione = descrizione;
	}

	public Prodotto(Sottocategoria sottocategoria, int codiceBarre,
			String descrizione, Integer idArg, Integer arg1, Integer arg2,
			Set inserziones, Set listaDesideriProdottis, Set listaSpesaProdottis) {
		this.sottocategoria = sottocategoria;
		this.codiceBarre = codiceBarre;
		this.descrizione = descrizione;
		this.idArg = idArg;
		this.arg1 = arg1;
		this.arg2 = arg2;
		this.inserziones = inserziones;
		this.listaDesideriProdottis = listaDesideriProdottis;
		this.listaSpesaProdottis = listaSpesaProdottis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_Prodotto", unique = true, nullable = false)
	public Integer getIdProdotto() {
		return this.idProdotto;
	}

	public void setIdProdotto(Integer idProdotto) {
		this.idProdotto = idProdotto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SottoCategoria", nullable = false)
	public Sottocategoria getSottocategoria() {
		return this.sottocategoria;
	}

	public void setSottocategoria(Sottocategoria sottocategoria) {
		this.sottocategoria = sottocategoria;
	}

	@Column(name = "CodiceBarre", unique = true, nullable = false)
	public int getCodiceBarre() {
		return this.codiceBarre;
	}

	public void setCodiceBarre(int codiceBarre) {
		this.codiceBarre = codiceBarre;
	}

	@Column(name = "Descrizione", nullable = false, length = 45)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "ID_Arg")
	public Integer getIdArg() {
		return this.idArg;
	}

	public void setIdArg(Integer idArg) {
		this.idArg = idArg;
	}

	@Column(name = "Arg1")
	public Integer getArg1() {
		return this.arg1;
	}

	public void setArg1(Integer arg1) {
		this.arg1 = arg1;
	}

	@Column(name = "Arg2")
	public Integer getArg2() {
		return this.arg2;
	}

	public void setArg2(Integer arg2) {
		this.arg2 = arg2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodotto")
	public Set getInserziones() {
		return this.inserziones;
	}

	public void setInserziones(Set inserziones) {
		this.inserziones = inserziones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodotto")
	public Set getListaDesideriProdottis() {
		return this.listaDesideriProdottis;
	}

	public void setListaDesideriProdottis(Set listaDesideriProdottis) {
		this.listaDesideriProdottis = listaDesideriProdottis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodotto")
	public Set getListaSpesaProdottis() {
		return this.listaSpesaProdottis;
	}

	public void setListaSpesaProdottis(Set listaSpesaProdottis) {
		this.listaSpesaProdottis = listaSpesaProdottis;
	}

}
