package hibernate;

// Generated 19-dic-2013 19.14.54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supermercato generated by hbm2java
 */
@Entity
@Table(name = "supermercato", catalog = "supermercati")
public class Supermercato implements java.io.Serializable {

	private Integer idSupermercato;
	private String nome;
	private Float latitudine;
	private Float longitudine;
	private Set inserziones = new HashSet(0);

	public Supermercato() {
	}

	public Supermercato(String nome, Float latitudine, Float longitudine,
			Set inserziones) {
		this.nome = nome;
		this.latitudine = latitudine;
		this.longitudine = longitudine;
		this.inserziones = inserziones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_Supermercato", unique = true, nullable = false)
	public Integer getIdSupermercato() {
		return this.idSupermercato;
	}

	public void setIdSupermercato(Integer idSupermercato) {
		this.idSupermercato = idSupermercato;
	}

	@Column(name = "Nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "Latitudine", precision = 12, scale = 0)
	public Float getLatitudine() {
		return this.latitudine;
	}

	public void setLatitudine(Float latitudine) {
		this.latitudine = latitudine;
	}

	@Column(name = "Longitudine", precision = 12, scale = 0)
	public Float getLongitudine() {
		return this.longitudine;
	}

	public void setLongitudine(Float longitudine) {
		this.longitudine = longitudine;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supermercato")
	public Set getInserziones() {
		return this.inserziones;
	}

	public void setInserziones(Set inserziones) {
		this.inserziones = inserziones;
	}

}
